# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ content ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ci_build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SDL_AUDIODRIVER: dummy # handles ALSA issues

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 2.7.18 # optional, default is 3.x

      # get/dl renpy src
      - name: cache rpy source
        id: cache-rpy
        uses: actions/cache@v2
        with:
            path: ~/renpy/
            key: ${{ runner.os }}-rpy

      - name: Download rpy source
        if: steps.cache-rpy.outputs.cache-hit != 'true'
        run: |
          wget https://www.renpy.org/dl/6.99.12.4/renpy-6.99.12.4-sdk.tar.bz2
          tar xf renpy-6.99.12.4-sdk.tar.bz2
          rm renpy-6.99.12.4-sdk.tar.bz2
          mv renpy-6.99.12.4-sdk renpy

      # get/download base mas
      - name: cache base MAS
        id: cache-mas
        uses: actions/cache@v2
        with:
            path: ~/mas0105/
            key: ${{ runner.os }}-mas

      - name: Download base MAS
        if: steps.cache-mas.outputs.cache-hit != 'true'
        run: |
          wget https://s3-us-west-2.amazonaws.com/monika-after-story/ddlc/mas.zip
          mkdir mas0105
          unzip mas.zip -d mas0105

      # copy files over
      - name: copy source over
        run: cp -Rf Monika\ After\ Story/* mas0105/

      # touch file for unstable so it doesn't raise exceptions for some things
      - name: exception skip for unstable
        if: github.ref == 'refs/heads/unstable'
        run: touch mas0105/trb

      # run sprite checkers
      - name: check sprites
        run: python tools/ghactions.py

      # lint renpy
      - name: rpy lint
        run: |
          cd renpy
          ./renpy.sh "../mas0105/" lint | grep -E -v "^$|Could not find image \(monika [0-9][^[:space:]]+ corresponding to attributes on say statement\.|'monika [0-9][^[:space:]]+' is not an image\.|The image named 'monika [0-9][^[:space:]]+ was not declared\."

      # distribute
      - name: rpy distribute
        run: |
          cd renpy
          ./renpy.sh launcher distribute "../mas0105/" --package Mod
